plugins = []
headers = []

[functions]

[functions."*"]

[build]
publish = "/Users/varundeshpande/Documents/WorldCupBeaut/public"
publishOrigin = "config"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]

[[redirects]]
from = "/"
to = "/sweepstake.html"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]